name: moodflix
description: Application Moodflix.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  dio: ^5.3.3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  get_it: ^7.6.4
  go_router: ^10.1.2
  intl: any
  logger: ^2.0.2+1
  provider: ^6.0.5
  shimmer: ^3.0.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
